# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9adedb2028ec050a19bf4a78451114262f37301ef0c7fbdee42cea52e18a4957691703daf78d09dfeadd5c4490cc06a7f156407f67fbb42ef285c214215521c8

test:
  secret_key_base: f5d1d3de1d7d9602ad9ddd774a2f1fbb498257b8c7b2b09a31533b6447ad06b88621c01f7b5ea9e7b609086fcb445df721fe53a199209fb77edf049b61c44677

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
